### ISSUE TITLE
What day should we meet on?

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/reno#1]
I am thinking the second Thursday of the month.  What does everyone think?

**Comment by ccothrun** [comment]
Everything but Monday night is good for me.

**Comment by drubarth** [comment]
That works well because the /dev/reno group meets on the 4th Monday of the month which spaces it out.

**Comment by jbgarr** [comment]
That sounds good to me!

**Comment by jordanpapaleo** [comment]
January 10th at 6pm for the initial BeerJS Reno!
