### ISSUE TITLE
Thursday September 12 @ 6:00pm: Lightning Talks

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/reno#15]
# Updated to a social event

## We are meeting at [Rue Bourbon](https://www.ruebourbonreno.com/):

```
1401 S Virginia St
Reno, NV 89502
```

## Announcements

Jordan will be out of town.  Wes will be running the event!

## Shout out

- Rue and Bourbon for giving us a home!

**Comment by monkseal** [comment]
I can do 10 minutes on benefits of functional programming with some examples from [Ramda](https://ramdajs.com/) library.

**Comment by jordanpapaleo** [comment]
That would be awesome 

Sent from my smallest computer

On Aug 23, 2019, at 3:13 PM, Kevin English <notifications@github.com> wrote:

I can do 10 minutes on benefits of functional programming with some examples from Ramda library.

**Comment by jordanpapaleo** [comment]
@monkseal You are the only individual who has signed up.  Thank you.  We are going to switch to a social this month.  Thank you for offering to present.
