### ISSUE TITLE
Thursday December 12 @6:00 pm: Lightning Talk

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/reno#18]
All I want for Christmas is LIGHTNING TALKS!!!

# Lightning talk [Meetup Link](https://www.meetup.com/RenoJS/events/266077683)

Comment on this issue with ideas of things you would like to hear about or things you would like to share.

**Each time block is for presentations only, no questions.**

After all lighting talks are complete, presenters can casually answer questions if they want to.

## Topics and Times

- 5:45: Cheers get your Beers
- 6:00:  `Jordan` Welcome aficionado and official heckler
- 6:05:  `Wesley Kepke` on automated testing using WebdriverIO
- 6:15: `Robert Biggs` TEA (The Elm Architecture) for React
- 6:25: `Juliann Talkington` Synthetic Biology Programming
- 6:35: `Rachel Macintyre` Pop-up coworking
- 6:45: `Jason Alvernaz` Gatsby
- 6:55: `Troy Weber` Observables with RxJS

## We are meeting at [Reno Collective](https://renocollective.com):

```
1515 Plumas Street
Reno, NV 89509
```

**Comment by wesleykepke** [comment]
I will be giving a talk on automated testing using WebdriverIO. Hope to see a lot of people there!

**Comment by jordanpapaleo** [comment]
**Some Ideas to help you to pick and present:**

- [React Conf 2019](https://conf.reactjs.org)... yeah that just happened and I missed it too.  Anything to report?
- FE Testing tech?
- Create React App v. Gatsby v. NextJS.  When should I do what?
- Will web components ever catch on?
- Whats `unstated.io`?
- Things I wish I knew in my first 2 years as a developer
- Database as a service for FE engineers that don't want to write a database
- Go over the different options you can pass to `addEventListener()`
- Compare/Contrast GraphQL to Rest APIs
- Which type of database should I use?
- Cool things a JS dev can do with Docker
- Netlify does more than deploy code
- A11Y Easy changes that make a big impact
- Why semicolons suck and why all bike sheds should be blue
- How to provide a radically candid code review

**Comment by rbiggs** [comment]
I could give a talk on a library I authored: Composi, Type Safe Functional Library with State Management.

**Comment by mattdaviscodes** [comment]
@jordanpapaleo Some sort of voting system for proposed topics might be a good idea. I'd be interested in a few of the ones you mentioned.

**Comment by jordanpapaleo** [comment]
@mattdavis1121 Those are for you to volunteer for and present the topic. So which one do you pick :)

**Comment by rbiggs** [comment]
OK, so according to feedback from last night, I'll do a talk on TEA (The Elm Architecture) for React.

**Comment by redbearin** [comment]
I am happy to talk about synthetic biology (what is it), the current stage of synthetic biology programming language development, how JS is being used in the synthetic biology space now, and how this emerging field may impact JS programmers.

**Comment by jcoryalvernaz** [comment]
I can do a talk about GatsbyJS.

**Comment by jordanpapaleo** [comment]
Awesome!  Please let me know if you want a company or something listed by your name.  Ill be adding this to Meetup soon and putting it out there for a larger group to view.

**Comment by redbearin** [comment]
Just my name, Juliann Talkington, is fine. Thanks!

**Comment by troywweber7** [comment]
I could do a talk on Observables (rxjs), but the 7:55 pm slot is a bit too late for me (wife and child and all that).

**Comment by jordanpapaleo** [comment]
That's supposed to be 6:55. Is that still to late?

**Comment by troywweber7** [comment]
@jordanpapaleo Sorry for the late response, didn't get a notification. That is better at the very least. If you have someone dying to give a presentation at that time, they can have it, otherwise, I'll make it work!

Do we have a screen to throw up one or two really simple examples? Or should I bring print-outs?

**Comment by jordanpapaleo** [comment]
We have a TV that has an hdmi and we also have apple air play.

**Comment by rbiggs** [comment]
So, what's the venue for this meetup since Rue Burbon isn't available?

**Comment by jordanpapaleo** [comment]
Working on it.  I think we can get the innovation center. 

Sent from my smallest computer

> On Dec 9, 2019, at 4:02 PM, Robert Biggs <notifications@github.com> wrote:
> 

﻿
So, what's the venue for this meetup since Rue Burbon isn't available?

**Comment by rbiggs** [comment]
According to the website it closes at 5PM: https://www.unr.edu/innevation/contact

**Comment by troywweber7** [comment]
@jordanpapaleo have you reached out to Darryl Rubarth (my boss) yet?

**Comment by jordanpapaleo** [comment]
@troywweber7 Darryl is the backup but it looks like we have the innovation center.  I have a call with them shortly to go over the details. 

@rbiggs They do know our start time.

**Comment by jordanpapaleo** [comment]
Hey Team!!! We are going to meet at the Reno Collective at 6. Its just up the street from Rue Bourbon.

https://www.google.com/maps/search/?api=1&query=Reno+Collective%2C+1515+Plumas+St%2C+Reno%2C+NV%2C+89509%2C+us&query_place_id=ChIJYWoSSctAmYARqK0fzQBqr48
