### ISSUE TITLE
January 10th at 6pm

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/reno#2]
# The first BeerJS event in Reno ever

## What to expect:

1. Nothing.  We have no agenda, no plan, and no expectations.
2. We are going to hang out and get to know each other a bit and see where this group goes.

## We are meeting at [Rue Bourbon](https://www.ruebourbonreno.com/):

```
1401 S Virginia St
Reno, NV 89502
```

There will be live music afterward too!

**Comment by arlt209** [comment]
sounds good to me :D

**Comment by jordanpapaleo** [comment]
https://www.meetup.com/RenoJS/events/257226391/
