### ISSUE TITLE
March 14 @ 6:00pm: Lightning Talks!

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/reno#4]
# Lightning talk time!

Reply to this issue with ideas of things you would like to hear about or things you would like to share.

**Topic ideas:** What you are learning about, a mistake you made and learned from, something you wish you knew a year ago, something you are working on, cache invalidation and naming things ;p

**Each time block is for presentations only, no questions.**

After all lighting talks are complete, presenters can casually answer questions.

## Topics and Times

- 6:10: Squashing your commits with interactive rebase
- 6:20: How to Type Lint JavaScript
- 6:30: A Shape of State
- 6:40: Formik: Taming React Forms
- 6:50: 

## We are meeting at [Rue Bourbon](https://www.ruebourbonreno.com/):

```
1401 S Virginia St
Reno, NV 89502
```

**Comment by jordanpapaleo** [comment]
I am thinking about doing a quick chat/demo on cross tab communication with JS.

**Comment by rbiggs** [comment]
## How to Type Lint JavaScript
Will show how to define JavaScript types with JSDoc and have live linting with TypeScript. 
Write JavaScript with type safety and rich Intellisense. Helps eliminate many tricky and hard to tract bugs and makes onboarding new team members easier.

**Comment by jordanpapaleo** [comment]
## Squashing your commits with interactive rebase

Does this look like your git history:

![image](https://user-images.githubusercontent.com/1728807/53762057-e7a8a700-3e7b-11e9-82b9-f8d602d2e8ee.png)

Yeah... we should talk about it and what we can do to make people think you can spell.

**Comment by jbgarr** [comment]
##A shape of state##

I'm going to talk about how to use a combination of an array and a dictionary to leverage the strengths of both as a potential way to store state. Get the speed of a one step lookup with a dictionary along with the utility of an array. Inspired by the NgRx Entity library.

**Comment by jbgarr** [comment]
## A Shape of State

I'm going to present on using a combination of an array and a dictionary to store state. Leveraging both allows for users to get the strengths of both - quick lookups in a dictionary along with all the utility of arrays. Inspired by the NgRx Entity library.

**Comment by hekaldama** [comment]
@jbgarr, reminds me of http://www.catb.org/esr/writings/taoup/html/ch01s06.html#id2878263.

**Comment by jordanpapaleo** [comment]
Sounds like @hekaldama would like to pick a couple of Unix philosophies and show how they apply to the web ;)

**Comment by hekaldama** [comment]
@jordanpapaleo I do have a "Unix Philosophy - Beyond the Pipe" talk I can do. Its currently more of a 30-40min type talk but could be worked into lightning format. I am unsure if I can do it this month though.

**Comment by wesleykepke** [comment]
### Formik: Taming React Forms

A demonstration of Formik, a small and performant library that takes the pain out of building React forms.

**Comment by wesleykepke** [comment]
For anyone interested in the Formik Demo code, you can find it here: https://github.com/wesleykepke/FormikDemo

**Comment by rbiggs** [comment]
For any one interested in reading my article on type safe JavaScript with JSDoc, here's the link: https://medium.com/@trukrs/type-safe-javascript-with-jsdoc-7a2a63209b76

**Comment by hekaldama** [comment]
@rbiggs @wesleykepke thanks!
