### ISSUE TITLE
Thursday June 13 @ 6:00pm: Lightning Talk

### ISSUE THREAD

**Issue by jordanpapaleo** [beerjs/reno#8]
# Lightning talk time! [Meetup Link](https://www.meetup.com/RenoJS/events/261484387/)

Reply to this issue with ideas of things you would like to hear about or things you would like to share.

I think I am going to try to live stream this with a GoPro, maybe

**Each time block is for presentations only, no questions.**

After all lighting talks are complete, presenters can casually answer questions if they want to

## Topics and Times

- 6:00: Welcome: Darryl Rubarth, Owner  at [Synap.io](https://synap.io/)
- 6:05: Deploying to Heroku: Joseph Ryan, QA Lead at [Clear Capital](https://www.clearcapital.com/)
- 6:15: Deploying node services to a multi-cloud environment on Cycle: [Chris](https://github.com/aubuchcl)
- 6:25: React.memo: Will Young, Engineer at [Alchemy](https://alchemy.us/)
- 6:35: Using React hooks with D3: [Jordan](https://github.com/jordanpapaleo), Engineer at [Theorem](https://theorem.co/)
- 6:45: Just an Overview of Vue [Blake](https://github.com/BlakeCampbells), Engineer at [benefit Many](https://www.benefitmany.com/)
- 7:55: Someting Cool TBD: [Wesley Kepke](https://github.com/wesleykepke), Engineer at [Alchemy](https://alchemy.us/)

## We are meeting at [Rue Bourbon](https://www.ruebourbonreno.com/):

```
1401 S Virginia St
Reno, NV 89502
```

**Comment by aubuchcl** [comment]
Deploying node services to a multi-cloud environment on Cycle, or something along those lines.  Can do it in 10 minutes

**Comment by BlakeCampbells** [comment]
I can do 10 minutes on VueJS "Just an Overview of Vue"

**Comment by jordanpapaleo** [comment]
You mean “An over vue” ;)

**Comment by jordanpapaleo** [comment]
@BlakeCampbells @aubuchcl would you like me to add a link for you or employer in the schedule?

**Comment by BlakeCampbells** [comment]
Sure it's https://www.benefitmany.com/

Thank you @jordanpapaleo

**Comment by jordanpapaleo** [comment]
Here are my slides: https://github.com/jordanpapaleo/presentation-d3-hooks
